# Generated by Django 5.0.8 on 2024-09-16 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='response',
        ),
    ]
